export const Questions = [
  {
    prompt: "What is the capital of France?",
    optionA: "Madrid",
    optionB: "Paris",
    optionC: "Berlin",
    optionD: "Rome",
    answer: "B",
  },
  {
    prompt: "Which planet is known as the Red Planet?",
    optionA: "Earth",
    optionB: "Jupiter",
    optionC: "Mars",
    optionD: "Venus",
    answer: "C",
  },
  {
    prompt: "What is the largest mammal on Earth?",
    optionA: "Elephant",
    optionB: "Blue Whale",
    optionC: "Great White Shark",
    optionD: "Giraffe",
    answer: "B",
  },
  {
    prompt: "How many continents are there?",
    optionA: "5",
    optionB: "6",
    optionC: "7",
    optionD: "8",
    answer: "C",
  },
  {
    prompt: "Who wrote 'Hamlet'?",
    optionA: "Charles Dickens",
    optionB: "William Shakespeare",
    optionC: "Leo Tolstoy",
    optionD: "Mark Twain",
    answer: "B",
  },
  {
    prompt: "What is the capital of India?",
    optionA: "Mumbai",
    optionB: "New Delhi",
    optionC: "Kolkata",
    optionD: "Chennai",
    answer: "B",
  },
  {
    prompt: "Which river is known as the 'Ganges of the South'?",
    optionA: "Godavari",
    optionB: "Krishna",
    optionC: "Kaveri",
    optionD: "Narmada",
    answer: "C",
  },
  {
    prompt: "Who was the first Prime Minister of India?",
    optionA: "Jawaharlal Nehru",
    optionB: "Sardar Patel",
    optionC: "Indira Gandhi",
    optionD: "Rajendra Prasad",
    answer: "A",
  },
  {
    prompt: "Which is the largest state in India by area?",
    optionA: "Madhya Pradesh",
    optionB: "Uttar Pradesh",
    optionC: "Rajasthan",
    optionD: "Maharashtra",
    answer: "C",
  },
  {
    prompt: "What is the national flower of India?",
    optionA: "Lotus",
    optionB: "Rose",
    optionC: "Jasmine",
    optionD: "Sunflower",
    answer: "A",
  },
  {
    prompt: "In which year did India gain independence?",
    optionA: "1942",
    optionB: "1945",
    optionC: "1947",
    optionD: "1950",
    answer: "C",
  },
  {
    prompt: "Which Indian city is known as the 'Silicon Valley of India'?",
    optionA: "Hyderabad",
    optionB: "Bangalore",
    optionC: "Pune",
    optionD: "Chennai",
    answer: "B",
  },
  {
    prompt: "What is the national animal of India?",
    optionA: "Elephant",
    optionB: "Tiger",
    optionC: "Lion",
    optionD: "Peacock",
    answer: "B",
  },
  {
    prompt: "Which festival is known as the 'Festival of Lights'?",
    optionA: "Eid",
    optionB: "Holi",
    optionC: "Diwali",
    optionD: "Christmas",
    answer: "C",
  },
  {
    prompt: "What is the official currency of India?",
    optionA: "Dollar",
    optionB: "Euro",
    optionC: "Rupee",
    optionD: "Yen",
    answer: "C",
  },
];
